// User Roles
const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  HR_ADMIN: 'HR_ADMIN',
  TEAM_LEAD: 'TEAM_LEAD',
  EMPLOYEE: 'EMPLOYEE',
  TELECALLER: 'TELECALLER',
  BDE: 'BDE'
};

// Employee Statuses
const EMPLOYEE_STATUS = {
  ACTIVE: 'ACTIVE',
  ON_LEAVE: 'ON_LEAVE',
  RESIGNED: 'RESIGNED',
  DEACTIVATED: 'DEACTIVATED'
};

// Lead Sources
const LEAD_SOURCES = {
  YELLOW_PAGES: 'YELLOW_PAGES',
  WEBSITE: 'WEBSITE',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA',
  TELECALLER: 'TELECALLER',
  BDE: 'BDE',
  BULK_IMPORT: 'BULK_IMPORT',
  EXCEL: 'EXCEL',
  OTHER: 'OTHER'
};

// Lead Priorities
const LEAD_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

// Initial Lead Statuses
const DEFAULT_LEAD_STATUSES = [
  'NEW',
  'PHONE_NOT_LIFTED',
  'CALL_ME_LATER',
  'INTERESTED',
  'NOT_INTERESTED',
  'READY_FOR_PAYMENT',
  'ALREADY_ENROLLED',
  'FOLLOW_UP_REQUIRED',
  'WRONG_NUMBER',
  'BUSY',
  'SWITCHED_OFF',
  'INVALID_NUMBER',
  'CALLBACK',
  'PAYMENT_COMPLETED',
  'ENROLLED',
  'CLOSED',
  'OTHER'
];

// Follow-up Statuses
const FOLLOW_UP_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  MISSED: 'MISSED',
  CANCELLED: 'CANCELLED'
};

// Payment Statuses
const PAYMENT_STATUS = {
  PENDING: 'PENDING',
  INITIATED: 'INITIATED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

// Listing Statuses
const LISTING_STATUS = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  EXPIRED: 'EXPIRED'
};

// Lock duration in minutes
const DEFAULT_LOCK_DURATION_MINUTES = 10;

module.exports = {
  ROLES,
  EMPLOYEE_STATUS,
  LEAD_SOURCES,
  LEAD_PRIORITY,
  DEFAULT_LEAD_STATUSES,
  FOLLOW_UP_STATUS,
  PAYMENT_STATUS,
  LISTING_STATUS,
  DEFAULT_LOCK_DURATION_MINUTES
};
